"""add category and tags with constraint names

Revision ID: 1c8754706c7e
Revises: a3f3fcc916d5
Create Date: 2026-01-16 09:55:12.655415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8754706c7e'
down_revision = 'a3f3fcc916d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_category_id', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_category_id', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
